name: Build EXE with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        python setup.py build

    - name: Zip build output
      run: Compress-Archive -Path build/exe.win-amd64-3.11/* -DestinationPath build/Sortly.zip

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sortly
        path: build/Sortly.zip
  release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Sortly

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: Sortly.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
